services:
  api:
    build: .
    ports:
      - "5000:5000"   # API disponível em http://localhost:5000/swagger
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=server=db;port=3306;database=MinhaBase;user=root;password=123456
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: MinhaBase
    command: >
      --innodb-buffer-pool-size=64M
      --max-connections=20
      --innodb-redo-log-capacity=32M
      --innodb-log-buffer-size=8M
      --innodb-flush-method=O_DIRECT
      --innodb-flush-log-at-trx-commit=2
      --sync-binlog=0
      --table-open-cache=200
      --table-definition-cache=400
      --performance-schema=OFF
      --skip-name-resolve
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    ports:
      - "3307:3306"   # MySQL do container acessível pelo host em localhost:3307
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123456"]
      timeout: 20s
      retries: 10

volumes:
  db_data:
